variables:
  USER_PROJECT: "onlineshop"
  PATCH_PROJECT: "/home/${USER_PROJECT}/${CI_PROJECT_NAME}"
stages:
  - build
  - deploy

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - dotnet restore
  tags:
    - online-shop-runner-dev-shell
  only:
    - tags

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - sudo cp -rf * ${PATCH_PROJECT}
    - sudo chown -R ${USER_PROJECT}. ${PATCH_PROJECT}
    - |
      pid=$( sudo netstat -tlpun | grep :5214 | awk '{print $7}' | cut -d '/' -f1) || true
      if [ -n "$pid" ]; then
          sudo kill -9 ${pid}
      fi
    - sudo su ${USER_PROJECT} -c "cd ${PATCH_PROJECT}; nohup dotnet run > log.txt 2>&1 &"
  tags:
    - online-shop-runner-dev-shell
  only:
    - tags
